### PR TITLE
initial update for .net core 3 preview2

### PR DESCRIPTION
**Pull request by ErikApption**
Runs electron.net with .net core 3 preview

### CODE REVIEW

**Comment by MaherJendoubi** [comment]
@ErikApption I wonder to know why not using the latest preview 5 of .NET Core 3

**Comment by MaherJendoubi** [comment]
@robertmuehsig https://dotnet.microsoft.com/platform/dotnet-standard#versions

**Comment by robertmuehsig** [comment]
Thats not what I asked. What do we need to do (during NuGet packaging etc.) to support netcore2.2 and netcore3.0? I know there are some long blogposts out there and when netcore3.0 is "mature" enough we will do this step, but until then I would need some good advice.

**Comment by MaherJendoubi** [comment]
You need to ship 2 different NuGet packages for instance 5.22.13 for netcoreapp2.2 and 5.30.13 for netcoreapp3.0. You could keep the master branch for netcoreapp3.0 and a second branch for netcoreapp2.2.

**Comment by robertmuehsig** [comment]
Checkout https://github.com/ElectronNET/Electron.NET/pull/313

**Pull request closed without merging**
