### PR TITLE
fix async issue where same port is considered open

### PR DESCRIPTION
**Pull request by netpoetica**
Solves https://github.com/ElectronNET/Electron.NET/issues/261

### CODE REVIEW

**Comment by asandersSAP** [comment]
Hey guys!  

When this will be merged?

**Comment by robertmuehsig** [comment]
Good to merge @GregorBiswanger? Looks good to me.

**Comment by rakista112** [comment]
Good evening, how may I use this in my project? We need this fix ASAP.

**Comment by netpoetica** [comment]
Until this is merged, you will need to use [.net/nuget locals](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals). You will need to use my fork of Electron.NET, in your local project. What I do right now is, I have a git repo which contains my fork of Electron.NET as a submodule, and then contains a .sln file alongside my fork of Electron.NET - then I use nuget locals, and a Makefile that helps to make sure I am compiling my fork w/ these changes. (Note: you may want to merge my fork on your local with most recent master, there likely have been changes since I made this PR)

My Directory structure:

```
~/workspace/my-project -> ls 
.gitmodules
Electron.NET/
Makefile
NuGet.config
my-project.sln
```

NuGet config for local packages:

```
~/workspace/my-project -> cat NuGet.config 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
    <clear />
    <add key="LocalDev" value="./Electron.NET/artifacts" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
</packageSources>
</configuration>
```

Makefile:

```
~/workspace/my-project-> cat Makefile 

# initialize application
init:
	git submodule init
	dotnet restore

build: clean
	# need to build to get updated opt/Host in my-project
	cd Electron.NET && ./buildReleaseNuGetPackages.sh
	dotnet build

# build for release (osx only)
# application will live at .bin/desktop
release: build
	cd my-project && electronize build /target osx

# run the application
start:
	cd my-project && ASPNETCORE_ENVIRONMENT=development electronize start

# run the application without dev mode
start-production:
	cd my-project && electronize start

clean:
	dotnet nuget locals all --clear
	dotnet restore
	dotnet clean
```

@rakista112 hope this helps

**Comment by netpoetica** [comment]
@GregorBiswanger I assure you, this should be merged :) I promise the JS force is strong with me ^-^

This is going to keep coming up in Electron.NET. I wouldn't be surprised if there are many people experiencing this problem and *not* commenting about it, but just giving up on Electron.NET because of inconsistent intermittent startup behavior.

**Pull request merged**
