### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Tum4ik**
Fixed documentation bug.

### CODE REVIEW

**Comment by robertmuehsig** [comment]
Both is possible, but I would say this is more convient. Agree @GregorBiswanger ?

**Comment by GregorBiswanger** [comment]
@robertmuehsig both works

**Comment by Tum4ik** [comment]
Unfortunately, for me the current variant is not working. I was not able to start the application.

**Comment by Tum4ik** [comment]
I suggest the most convenient way
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
      WebHost.CreateDefaultBuilder<Startup>(args)
        .UseElectron(args)
```

**Comment by robertmuehsig** [comment]
I'm ok with this, :shipit: @GregorBiswanger ?

**Comment by robertmuehsig** [comment]
I think this is ok - so I merged it. Sorry for the huge delay & thanks!

**Pull request merged**
