### PR TITLE
Update to .NET Core 3

### PR DESCRIPTION
**Pull request by raz-canva**
Using .NET Core 3 

Remove unused packages

### CODE REVIEW

**Comment by Daddoon** [comment]
For .NET Core 3.0 RTM working you need this to your PR:

- In your ElectronNET web app csproj, add the following lines under TargetFramework:

```xml
<TargetFramework>netcoreapp3.0</TargetFramework>
<AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
<AspNetCoreModuleName>AspNetCoreModule</AspNetCoreModuleName>
```

- In Startup.cs add **app.UseRouting();** before **app.UseEndpoints** call.

**Comment by raz-canva** [comment]
Would anyone be able to take over this PR? I think I it is pretty close to functioning

**Comment by robertmuehsig** [comment]
I was unable to pull this PR - maybe because you deleted the original branch? I (more or less) applied the same changes to a new branch and if everything works out, I might put up a beta with .NET Core 3 support on NuGet.

**Comment by Daddoon** [comment]
Hi @robertmuehsig , can you also take a look at my PR about AddExtension if you publish a beta ? I need this for my BlazorMobile plugin, it would be highly appreciated as it is blocking my ElectronNet implementation.

Thanks!

**Pull request closed without merging**
