### PR TITLE
Power monitor

### PR DESCRIPTION
**Pull request by gustavo-lara-molina**
powerMonitor
Monitor power state changes.

Event: 'lock-screen' macOS Windows
Emitted when the system is about to lock the screen.

Event: 'unlock-screen' macOS Windows
Emitted as soon as the systems screen is unlocked.

https://www.electronjs.org/docs/api/power-monitor

### CODE REVIEW

**Comment by GregorBiswanger** [comment]
**Thank you very much for your contribution!**
The PowerMonitor API has a few more events and functions. Can you also add these?

If you want you can send me your address via [Gitter](https://gitter.im/ElectronNET/community), then you will receive Electron.NET stickers as a thank you.

**Comment by gustavo-lara-molina** [comment]
Hi @GregorBiswanger , sure let me add the whole power Monitor related events and methods to this branch  👍🏼
Regards.

**Comment by GregorBiswanger** [comment]
I have already tested the existing one and it works wonderfully. 

It is already marked in the changelog :)
https://github.com/ElectronNET/Electron.NET/blob/master/Changelog.md

**Comment by hucg18** [comment]
Hi, 

I just tested these features in OS X and they worked just fine
Screen Shot 2020-05-13 at 17 24 40

**Pull request merged**
