### PR TITLE
Live Reload Implemented

### PR DESCRIPTION
**Pull request by syedadeel2**
Hello,

I have enabled the Live Reload feature in ElectronNET CLI with new command "debug". This feature helps me a lot to increase my development when I need to test my methods with an electron window.

To view the video demo please click on this http://somup.com/cYej1tha0Q link

To enable the LiveReload you have to set the LiveReload variable to true see the below code in Startup.cs

```
public async void ElectronBootstrap()
 {
 var browserWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions {
                Width = 1500,
                Height = 940,
                Show = true,
                LiveReload = true,
                DarkTheme = true
 });
await browserWindow.WebContents.Session.ClearCacheAsync();
browserWindow.OnReadyToShow += () => browserWindow.Show();
browserWindow.SetTitle("LiveReload Demo");
}
```

If you like this feature to be apart of ElectronNET please approve and merge and I create an actual demo video for step by step how to enable live reload with ElectronNET.

Thank yous

### CODE REVIEW

**Comment by syedadeel2** [comment]
@GregorBiswanger

**Comment by syedadeel2** [comment]
> You removed important code in `ElectronNET.Host/main.js` - Please integrate again and see that your solution runs with it

Will do that asap

**Comment by GregorBiswanger** [comment]
@syedadeel2 If it helps you, here are a few tips for live reload in this issue >> #305

**Comment by syedadeel2** [comment]
> @syedadeel2 If it helps you, here are a few tips for live reload in this issue >> #305

Thank you, I'll take care of that - just a little busy with office stuff once finish I will push the new changes asap. Thank you once again.

**Comment by GregorBiswanger** [comment]
I think I have a solution how we can enable a reload feature with less code... so that you only need a command like `electronize start /watch` - The best thing to do is contact me via the gitter..

**Comment by syedadeel2** [comment]
> I think I have a solution how we can enable a reload feature with less code... so that you only need a command like `electronize start /watch` - The best thing to do is contact me via the gitter..

Sure, I'll contact you asap. whats the URL for Gitter?

**Comment by syedadeel2** [comment]
> > I think I have a solution how we can enable a reload feature with less code... so that you only need a command like `electronize start /watch` - The best thing to do is contact me via the gitter..
> 
> Sure, I'll contact you asap. whats the URL for Gitter?

nevermind I found it.

**Comment by GregorBiswanger** [comment]
https://gitter.im/ElectronNET/community - write me a dm @BFreakout

**Comment by syedadeel2** [comment]
starting work on this now...

**Comment by GregorBiswanger** [comment]
I write you on gitter...

**Comment by syedadeel2** [comment]
> I write you on gitter...

Yes, I saw that I have already fixed and finished the Live-Reload with /watch and only 1 file get changed lesser code :) going to push tonight after testing.

**Pull request closed without merging**
