### PR TITLE
Implement NativeImage support, fixes #14

### LINKED ISSUE #14: Implement Electron´s NativeImage
The problem with NativeImage is that it uses Nodejs buffer.
I need a solution for Nodejs buffer to .NET Core buffer.
I have no experience with buffer, maybe it is easy to implement.

NativeImage:
https://electron.atom.io/docs/api/native-image/

Nodejs Buffer:
https://nodejs.org/api/buffer.html#buffer_class_buffer

.NET Core Buffer:
https://docs.microsoft.com/de-de/dotnet/api/system.buffer?view=netcore-2.0

### PR DESCRIPTION
**Pull request by ThrDev**
This is a long time running of reading documentation and source code within Electron/Chromium itself to see how the image handling is implemented.

The main conversion that happens in this bridge is that we have an array of (float)scaleFactor=>System.Drawing.Image. We serialize these by creating a json object with the scaleFactor as the key, and a base64 encoded representation of the System.Drawing.Image. From there, we send over the serialized data. The javascript picks it up and creates an empty nativeImage. Then, we add all the representations with scale factor to the electron nativeImage.

Everything image manipulation-wise happens on the dotnet side. The only thing this is currently used for with the bridge is clipboard image reading/writing. Hopefully we can add NativeImage support to more things soon, such as Tray Icons, etc.

### CODE REVIEW

**Comment by GregorBiswanger** [comment]
Wow! Thanks for your great work! 

I will do a review as soon as possible and deliver it to our next update.

**Comment by GregorBiswanger** [comment]
Do you have an idea why the build fails with Travis-CI?

**Comment by GregorBiswanger** [comment]
Did you bring everything together on the basis of Electron.NET 8.31.1?

**Comment by ThrDev** [comment]
Hi Gregor, let me look into why the demo app is not working for you.
I made sure to delete my nuget package cache, so it was up to date with the latest built package.

I just pulled upstream master, and ran the app, and it seemed to work for me. The box next to copy is for pasting images into, i.e ctrl+v. 

I've attached a video to show you the demo, as seen below.
https://shotr.dev/8sE17

Thanks!

**Comment by GregorBiswanger** [comment]
Thank you very much for the great work! With the next update 8.31.2 your feature will be included :) That enriches the community very much ... if you send me your address via Gitter, I can send you Electron.NET stickers if you want :)

We have the demo app again separately.. would be cool if you could test it there again... as soon as our update has been published, it will also be used there:
https://github.com/ElectronNET/electron.net-api-demos

**Comment by ThrDev** [comment]
> We have the demo app again separately.. would be cool if you could test it there again... as soon as our update has been published, it will also be used there:
> https://github.com/ElectronNET/electron.net-api-demos

I will submit a PR soon with changes to the demo that includes the support for showing off the copy + paste for clipboard and images.

**Pull request merged**
