### PR TITLE
description added to package.json

### LINKED ISSUE #432: Description bug in setup file
- **Version**: v9.31.1
- **Target**: .NET Core 3.1

Try to customize description in electron.manifest.json
  "author": "Constantine",
  "description": "Test"
The Setup file description is still "Electron-Host for Electron.NET." And also Comment of the lnk file after installation "Electron-Host for Electron.NET."

### PR DESCRIPTION
**Pull request by BurtsevC**
Description bug fix #432

### CODE REVIEW

**Comment by GregorBiswanger** [comment]
Thank you for your contribution! Write me your postal address on Gitter and you will get Electron.NET sticker :)

**Comment by GregorBiswanger** [comment]
Did you also test whether it takes over the description at runtime?

**Comment by MarkBQE** [comment]
I had a similar issue, in release version it is fine. However after the last update it got fixed both in dev as well as release

**Comment by BurtsevC** [comment]
> Did you also test whether it takes over the description at runtime?

I have checked that the Setup file description changed as well as Comment of the lnk file after installation. But an .exe file of the program has the same File description as Product name. I also saw the same behavior in the "pure" Electron.

**Pull request merged**
