### PR TITLE
Upgrade to .NET 8.0

### PR DESCRIPTION
**Pull request by Lemon73-Computing**

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Quick question: What does work by having this changed? Right now you can use Electron.NET with .NET 6 onwards; this change would make it only compatible to .NET 8 onwards. I don't see any .NET 8 API being used, so I wonder - is that really necessary?

**Comment by Lemon73-Computing** [comment]
Now, `electronize` only runs on .net 6. However .net 6 is close to EoS. We can use `electronize` on new version (.net 8) project by my changed.

**Comment by FlorianRappl** [comment]
> Now, `electronize` only runs on .net 6. However .net 6 is close to EoS. We can use `electronize` on new version (.net 8) project by my changed.
> 
> (Relate issue: #837)

Yeah I agree the CLI should work on more targets. Potentially making the CLI independent of .NET (i.e., self-contained) would just solve this. This way we could go for .NET 8, but as its deployed as a self-contained CLI it would also work on any (older - or more recent) platform - escaping the need to install a fixed version of .NET.

I would say let's merge this and let's improve the CLI in the future.

**Review by FlorianRappl — APPROVED** [review]

**Comment by Lemon73-Computing** [comment]
Added:
```xml
<PublishSelfContained>true</PublishSelfContained>
```

**Pull request merged**
