### PR TITLE
Added Target option for Start command

### LINKED ISSUE #271: Support electronize start target 32bit
I'm use this library for develop a software but my software depend on some library only run 32bit process. So i use win 10 x64 for develop and when i run this command "electronize start" it will trigger "dotnet publish x64". so i my project only target x86.

### PR DESCRIPTION
**Pull request by callumhutchy**
Uses the same structure as the /target for BuildCommand, changes the 'path' option to follow the same system /path <path>. 
Allows platform targeting when testing applications, which is necessary when using certain libraries.
Fixes #271

### CODE REVIEW

**Comment by robertmuehsig** [comment]
@callumhutchy Sorry for the huge delay. In threory your PR looks good and makes sense, unfortunately there is a merge conflict because of recent changes. 
If you are still interested to see this feature in a future release I'm happy to merge if you could resolve the merge conflict.

**Comment by callumhutchy** [comment]
@robertmuehsig I'll review this at some point over the weekend

**Comment by gabecook** [comment]
This may help. It's what we are using with the current version of ElectronNET.

https://github.com/ElectronNET/Electron.NET/pull/463

**Comment by GregorBiswanger** [comment]
We use #463

**Pull request closed without merging**
